name: Whisperer pipeline check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Whisperer_Unit_Testing:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: false
          # virtualenvs-path: ~/my-custom-path
          installer-parallel: true
      - run: mkdir -p  /home/runner/work/whisperer/whisperer/data/raw_files
      - run: pwd
      - run: sudo apt-get install libsndfile1-dev
      - run: yt-dlp -x --downloader aria2c --audio-format wav -o data/raw_files/lex_biologist.wav "https://www.youtube.com/watch?v=gnUdEYTZAA0"
      - run: yt-dlp -x --downloader aria2c --audio-format wav -o data/raw_files/lex_levin2.wav "https://www.youtube.com/watch?v=yRMIZrn8IuE"
      - run: ls data/raw_files 
      - run: poetry install
      - run: poetry run whisperer_ml --debug convert data/
      - run: poetry run whisperer_ml --debug diarize data/
      - run: poetry run whisperer_ml --debug auto-label data/ 2
      - run: poetry run whisperer_ml --debug transcribe data/ dataset
      - run: cat data/datasets/dataset_42/metadata.txt


      # - run: yt-dlp -x  --downloader aria2c --audio-format wav -o data/raw_files/lex_debate.wav "https://www.youtube.com/watch?v=opMZib2qqeM"
      # - run: yt-dlp -x --downloader aria2c --audio-format wav -o data/raw_files/lex_carmack1.wav "https://www.youtube.com/watch?v=xzPuGf89vpI"
      # - run: yt-dlp -x --downloader aria2c --audio-format wav -o data/raw_files/lex_levin0.wav "https://www.youtube.com/watch?v=ZSddchIGNG0"
      # - run: yt-dlp -x  --downloader aria2c --audio-format wav -o data/raw_files/lex_levin1.wav "https://www.youtube.com/watch?v=wNqhp5qiufA"